name: CI
on: [push]

jobs:
  build:
    name: Build and test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: '1.12'
        id: go

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -v ./...
